server:
   port: 8088    
   error:
      whitelabel:
         enabled: false    

spring:
  datasource:
    platform: MySQL
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/polyclinic?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: sapar12

  jpa:
    hibernate:
       ddl-auto: update
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL55Dialect
    generate-ddl: true